[platformio]
default_envs = brain-control, brain-connectivity
src_dir = firmware

[env]
platform = espressif32 @ 7.0.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_compat_mode = strict
lib_deps =
    bblanchon/ArduinoJson @ 7.1.0
    adafruit/Adafruit ADS1X15 @ 2.5.0
    adafruit/RTClib @ 2.1.4
    paulstoffregen/OneWire @ 2.3.8
    milesburton/DallasTemperature @ 3.11.0
    knolleary/PubSubClient @ 2.8.0
    SPI
    Wire

[env:brain-control]
build_src_filter = +<brain-control/src/>
lib_ignore =
    ESPAsyncWebServer
    AsyncTCP
lib_deps =
    ${env.lib_deps}
    FS
    LittleFS
build_flags =
    -I firmware/brain-control/include
    -D BRAIN_CONTROL

[env:brain-connectivity]
build_src_filter = +<brain-connectivity/src/>
lib_deps =
    ${env.lib_deps}
    ESP32Async/ESPAsyncWebServer @ 3.7.0
    ESP32Async/AsyncTCP @ 3.3.5
    WiFi
    Update
    ArduinoOTA
    FS
build_flags =
    -I firmware/brain-connectivity/include
    -D BRAIN_CONNECTIVITY
