[platformio]
default_envs = brain-control, brain-connectivity
src_dir = firmware

[env]
platform = espressif32 @ 6.6.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    adafruit/RTClib @ ^2.1.3
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    knolleary/PubSubClient @ ^2.8
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    SPI

[env:brain-control]
build_src_filter = +<brain-control/src/>
build_flags =
    -I firmware/brain-control/include
    -D BRAIN_CONTROL

[env:brain-connectivity]
build_src_filter = +<brain-connectivity/src/>
build_flags =
    -I firmware/brain-connectivity/include
    -D BRAIN_CONNECTIVITY
